[project]
name = "graphly"
version = "0.1.0"
description = "Python code library to communicate with different graph technologies, graphs and ontologies."
authors = [{name="GaÃ©tan Muck"}]
dependencies = []

requires-python = ">=3.8"